#############
# res 256 #
#############

comodgan_mapping:
  super_cfg: stylegan2_mapping
  symbol: comodgan
  type: comodgan_mapping

comodgan_e256:
  symbol: comodgan
  type: comodgan_encoder
  args:
    resolution: 256
    ic_n: 4
    oc_n: 1024
    ch_base: 32768
    ch_max: 512
    use_fp16_before_res: null
    resample_filter: [1, 3, 3, 1]
    activation: lrelu_agc(alpha=0.2, gain=sqrt_2, clamp=256)
    mbstd_group_size: 0
    mbstd_c_n: 0
    c_dim: null
    cmap_dim: null
    use_dropout: True
    has_extra_final_layer: False
  pretrained: null

comodgan_s256:
  symbol: comodgan
  type: comodgan_synthesis
  args:
    w_dim : 512
    w0_dim : 1024
    resolution: 256
    rgb_n   : 3
    ch_base : 16384
    ch_max  : 512
    use_fp16_after_res : null
    resample_filter : [1, 3, 3, 1]
    activation : lrelu_agc(alpha=0.2, gain=sqrt_2, clamp=256)
  pretrained: null

comodgan_d256:
  super_cfg: stylegan2_discriminator
  symbol: comodgan
  type: comodgan_discriminator
  args:
    ic_n: 4
    use_fp16_before_res : null

comodgan_g256:
  symbol: comodgan
  type: comodgan_generator
  args:
    mapping: MODEL(comodgan_mapping)
    encoder: MODEL(comodgan_e256)
    synthesis: MODEL(comodgan_s256)
  pretrained: null

################
# res512 #
################

comodgan_mapping_512:
  super_cfg: comodgan_mapping
  args:
    num_ws: 16

comodgan_e512:
  super_cfg: comodgan_e256
  args:
    resolution: 512

comodgan_s512:
  super_cfg: comodgan_s256
  args:
    resolution: 512

comodgan_d512:
  super_cfg: comodgan_d256
  args:
    resolution: 512

comodgan_g512:
  symbol: comodgan
  type: comodgan_generator
  args:
    mapping: MODEL(comodgan_mapping_512)
    encoder: MODEL(comodgan_e512)
    synthesis: MODEL(comodgan_s512)
  pretrained: null
